apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000        # What you want to port-forward to
      targetPort: 8000  # Matches what the container is listening on
  type: ClusterIP
