apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80           # External service port (standard web port)
      targetPort: 3001   # Must match containerPort
      nodePort: 30001    # Explicit NodePort (30000-32767 range)
  type: NodePort
