apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: khadija2557/my-fusion-ecommerce-frontend:latest
          ports:
            - containerPort: 3001  # Keep this if your React app runs on 3001
          env:
            - name: REACT_APP_BACKEND_URL
              # Change to 5000 (standard backend port) or your actual backend port
              value: "http://backend-service:5000"  
          # REMOVE the volumeMounts and volumes sections completely
          # They're causing issues and aren't needed for a containerized app