name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment (PowerShell)
      shell: pwsh
      run: |
        Write-Output "Configuring Docker to use Minikube's daemon..."
        minikube -p minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Frontend Docker image
      run: |
        cd frontend
        docker build -t khadija2557/my-fusion-ecommerce-frontend:latest .
        
    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t khadija2557/my-fusion-ecommerce-backend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Frontend image to Docker Hub
      run: docker push khadija2557/my-fusion-ecommerce-frontend:latest

    - name: Push Backend image to Docker Hub
      run: docker push khadija2557/my-fusion-ecommerce-backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f configmap.yaml
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f backend-service.yaml
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f frontend-service.yaml
